FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry

COPY apps/worker/pyproject.toml apps/worker/poetry.lock* ./
RUN poetry config virtualenvs.create false && poetry install --no-root

COPY apps/worker/ .

CMD ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
