from typing import Protocol
from uuid import UUID
from app.domain.entities.tenant import Tenant

class TenantRepository(Protocol):
    async def create(self, tenant: Tenant) -> Tenant: ...
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_slug(self, slug: str) -> Tenant | None: ...
    async def update(self, tenant: Tenant) -> Tenant: ...
